# Generated by Django 4.2.5 on 2023-09-18 10:54

import autoslug.fields
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Brand",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=150, unique=True)),
                (
                    "image",
                    models.ImageField(
                        null=True, upload_to="images/", verbose_name="Зображення"
                    ),
                ),
                ("country", models.CharField(max_length=100)),
                ("description", models.TextField()),
            ],
            options={
                "verbose_name": "Бренд",
                "verbose_name_plural": "Бренди",
            },
        ),
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=150, unique=True)),
                ("description", models.TextField()),
                (
                    "image",
                    models.ImageField(
                        null=True, upload_to="images/", verbose_name="Зображення"
                    ),
                ),
                (
                    "slug",
                    autoslug.fields.AutoSlugField(
                        default="", editable=False, populate_from="name", unique=True
                    ),
                ),
            ],
            options={
                "verbose_name": "Категорія",
                "verbose_name_plural": "Категорії",
            },
        ),
        migrations.CreateModel(
            name="FeedbackMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=100, verbose_name="Им'я користувача"),
                ),
                ("message", models.TextField(verbose_name="Повідомлення")),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="Створено"
                    ),
                ),
                ("new", models.BooleanField(default=True, verbose_name="Нове")),
            ],
            options={
                "verbose_name": "Повідомлення",
                "verbose_name_plural": "Повідомлення",
            },
        ),
        migrations.CreateModel(
            name="Post",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(max_length=200, verbose_name="Заголовок посту"),
                ),
                ("content", models.TextField(verbose_name="Зміст посту")),
                (
                    "pub_date",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        verbose_name="Дата публикації",
                    ),
                ),
                (
                    "photo",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="post_photos/",
                        verbose_name="Фотографія",
                    ),
                ),
            ],
            options={
                "verbose_name": "Стаття",
                "verbose_name_plural": "Статті",
            },
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="Назва")),
                ("description", models.TextField(verbose_name="Опис")),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Ціна"
                    ),
                ),
                (
                    "slug",
                    autoslug.fields.AutoSlugField(
                        default="", editable=False, populate_from="name", unique=True
                    ),
                ),
                (
                    "article",
                    models.PositiveIntegerField(unique=True, verbose_name="Артикул"),
                ),
                (
                    "brand",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="store.brand",
                        verbose_name="Бренд",
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="store.category",
                        verbose_name="Категорія",
                    ),
                ),
            ],
            options={
                "verbose_name": "Товар",
                "verbose_name_plural": "Товари",
            },
        ),
        migrations.CreateModel(
            name="Subcategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=150, unique=True, verbose_name="Назва підкатегорії"
                    ),
                ),
                ("description", models.TextField(verbose_name="Опис підкатегорії")),
                (
                    "image",
                    models.ImageField(
                        null=True,
                        upload_to="images/",
                        verbose_name="Зображення підкатегорії",
                    ),
                ),
                (
                    "slug",
                    autoslug.fields.AutoSlugField(
                        default="", editable=False, populate_from="name", unique=True
                    ),
                ),
                (
                    "parent_category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subcategories",
                        to="store.category",
                        verbose_name="Батьківська категорія",
                    ),
                ),
            ],
            options={
                "verbose_name": "Підкатегорія",
                "verbose_name_plural": "Підкатегорії",
            },
        ),
        migrations.CreateModel(
            name="ProductImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="images/")),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="store.product"
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="product",
            name="subcategory",
            field=models.ForeignKey(
                blank=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="store.subcategory",
                verbose_name="Підкатегорія",
            ),
        ),
    ]
