# Generated by Django 4.2.5 on 2023-09-20 19:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_discountcondition_delete_quillpost'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DiscountCondition',
        ),
    ]
