# Generated by Django 4.2.5 on 2023-09-25 19:02

from django.db import migrations
import django_ckeditor_5.fields


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_delete_discountcondition'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='content',
            field=django_ckeditor_5.fields.CKEditor5Field(verbose_name='Зміст посту'),
        ),
    ]
