# Generated by Django 4.2.5 on 2023-10-09 13:14

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("store", "0008_banner"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Banner",
        ),
    ]
