# Generated by Django 4.2.5 on 2024-02-02 13:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('store', '0009_delete_banner'),
    ]

    operations = [
        migrations.CreateModel(
            name='SalesStatistics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_sales', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Сумма продаж')),
                ('total_quantity', models.PositiveIntegerField(default=0, verbose_name='Количество единиц')),
                ('share_of_total', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Доля продаж %')),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='store.product', verbose_name='Товар')),
            ],
            options={
                'verbose_name': 'Статистика продаж',
                'verbose_name_plural': 'Статистика продаж',
            },
        ),
    ]
